### ISSUE TITLE
Set up branch coverage

### ISSUE THREAD

**Issue by garious** [loomprotocol/loom#2]

**Comment by garious** [comment]
Here's what I had in mind originally. The approach looks good but it's a year old now, requires a patch to LLVM's compiler-rt and seems not to have gained traction in the community.
https://users.rust-lang.org/t/howto-generating-a-branch-coverage-report/8524

If you ignore branch coverage this seems good, but looks unmaintained:
https://github.com/huonw/travis-cargo

Then there's a bunch of wrappers of `kcov`. Seems popular, integrates with Travis and coveralls.io, but kcov is not packaged and needs to be built from source.
https://crates.io/crates/cargo-travis/

I gave it a go, but it needs some hacks on macOS. Thinking we can set it up for the Travis build and otherwise ignore it day to day. Not ideal, but it's something.

**Comment by garious** [comment]
I wasn't able to find anything low cost enough to justify adding to the project. Let's revisit this another day. Seems like this kind of tooling will eventually be added to cargo.

**Comment by aeyakovenko** [comment]
https://github.com/rust-lang/rfcs/issues/646
still open
